[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ac = "9zuEtiy6MeucRyUTkUTy8ydX9A35cKBawnrHkU3CULvf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
